### ISSUE TITLE
La lista no se puede puede crear con elementos

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp2#1]
Los casos de prueba

https://github.com/acurber91/tsiot_tp2/blob/2e9c83aa46fa6d394f973c80cffb881025a26b4f/test/test_lista.js#L23

y 

https://github.com/acurber91/tsiot_tp2/blob/2e9c83aa46fa6d394f973c80cffb881025a26b4f/test/test_lista.js#L43

Son en realidad el mismo porque la lista no se puede crear con un elemento, sino que la lista se crea vacía y se le agregan elementos.

**Comment by acurber91** [comment]
Excelente observación. Corregí el texto de ambos casos de prueba.
