### ISSUE TITLE
Ls cláusulas it solo deberían contener verificaciones de resultados

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp2#2]
Las clausulas *_decribe_* son las que deberían utilizarse para generar las condiciones y llamar a la funciones de prueba y las clausulas *_it_* para verificar los resultados

https://github.com/acurber91/tsiot_tp2/blob/2e9c83aa46fa6d394f973c80cffb881025a26b4f/test/test_lista.js#L45-L48

**Comment by acurber91** [comment]
Genial. Removí la condición y separé más los casos de prueba.
