### ISSUE TITLE
Los elementos no se agregan ni al principio ni al final

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp2#4]
Los elementos se agregan a la lista, ni al principio ni al final porque la lista en si misma no necesita estar ordenada. El requisito pide recuperar una lista con todas las claves y esa lista que que obtiene como resultado de una función es la que debe estar ordenada.

https://github.com/acurber91/tsiot_tp2/blob/2e9c83aa46fa6d394f973c80cffb881025a26b4f/test/test_lista.js#L50-L58

**Comment by acurber91** [comment]
Esto fue una mala interpretación de los requerimientos. Ya está resuelto también y lo dividí en dos casos de prueba distintos. Para reflejar estos cambios, se actualizó el archivo README.
