### ISSUE TITLE
No se deben implementar funciones que los requisitos no pidan

### ISSUE THREAD

**Issue by evolentini** [acurber91/tsiot_tp2#5]
En los requisitos propuestos no se pide una función que devuelva todos los pares almacenados en la lista. No se deben agregar funciones que no están en los requisitos propuestos, y ademas esta prueba es dependiente de la implementación de la lista, lo cual no es bueno.

https://github.com/acurber91/tsiot_tp2/blob/2e9c83aa46fa6d394f973c80cffb881025a26b4f/test/test_lista.js#L62

La forma correcta de hacer esta prueba seria obtener la lista de todas las claves y después con un lazo  para cada clave buscar el valor. 

La otra forma más simple es buscar la clave que acabamos de borrar y asegurarnos de que no se la encuentra.

**Comment by acurber91** [comment]
Perfecto, modifiqué el caso de prueba para que no se encuentre la clave que se agregó.
